### ISSUE TITLE
Slow loading tiles, javascript lockup when zooming in Chrome

### ISSUE THREAD

**Issue by mlake** [mapbox/mapbox.js#1062]
Firefox and Safari work fine.

My Chrome version: 45.0.2454.101 (64-bit)

Here's the live example: http://techtour.cvilleinnovation.org/
Try clicking around on the 'business' entries and compare to firefox.

Using 0.7.5 leaflet with mapbox 2.2.2

**Comment by jfirebaugh** [comment]
I'm not sure I see any noticeable difference between Chrome and Firefox. Can you post numbers from the developer tools, or a screen capture of what you're referring to?

**Comment by clayne11** [comment]
I'm seeing HUGE issues in Chrome as well. Zooming can lock up the map for up to 10-15 seconds. No problems at all on Firefox or Safari.

**Comment by jfirebaugh** [comment]
@clayne11 What Mapbox.js version? There was an issue caused by a Chrome regression that fits your description which was resolved in 2.2.2.

**Comment by clayne11** [comment]
Looks like I was using 2.1.5. Upgrade to 2.2.2 and that issue is gone.

**Comment by tmcw** [comment]
Fixed in 2.2.2

**Comment by Samrudhi** [comment]
Hi, 
I am using mapbox version 2.2.2 and my Chrome version: 45.0.2454.101 (64-bit). I still see the issue of mapbox tiles loading significantly slower than in Safari. Can this be optimized more for chrome?

Thanks!
